version: "3.9"
name: users-service
services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: "users_db"
      POSTGRES_USER: "go_user"
      POSTGRES_PASSWORD: "go_password"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - main-network

  users:
    build: .
    container_name: service
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: "postgres://go_user:go_password@database:5432/users_db?sslmode=disable"
      SERVICE_PORT: 80
      SERVICE_TIMEOUT: 5
    ports:
      - "8081:80"
    networks:
      - main-network


volumes:
  pg-data:

networks:
  main-network:
    driver: bridge